export const data = [
    {
      id: 1,
      first_name: "Cherie",
      age: '6 years',
      size: 'Large',
      vaccinated: 'Yes',
      neutered: 'Yes',
      breed: 'Pitbull',
      email: "chair0@friendfeed.com",
      gender: "Male",
      ip_address: "30.12.148.95",
      date: "2021-07-18T01:03:25Z",
      image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      avatar: "https://robohash.org/inutofficia.png?size=150x150&set=set1",
    },
    {
      id: 2,
      first_name: "Catharina",
      age: '2 years',
      size: 'Medium',
      vaccinated: 'Yes',
      neutered: 'No',
      breed: 'German Shepherd',
      email: "cbierman1@umn.edu",
      gender: "Male",
      ip_address: "66.106.209.53",
      date: "2020-09-12T19:22:35Z",
      image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
      avatar: "https://robohash.org/quiaatcommodi.png?size=150x150&set=set1",
    },
    {
      id: 3,
      first_name: "Vernen",
      age: '2 months',
      size: 'Small',
      vaccinated: 'No',
      neutered: 'Yes',
      breed: 'Pitbull',
      email: "vdummigan2@lulu.com",
      gender: "Female",
      ip_address: "117.117.129.12",
      date: "2021-04-10T21:22:32Z",
      image: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      avatar: "https://robohash.org/voluptasquisaut.png?size=150x150&set=set1",
    },
    {
      id: 4,
      first_name: "Vernen",
      age: '3 years',
      size: 'Medium',
      vaccinated: 'Yes',
      neutered: 'No',
      breed: 'Labrador',
      email: "vdummigan2@lulu.com",
      gender: "Female",
      ip_address: "117.117.129.12",
      date: "2021-04-10T21:22:32Z",
      image: "http://dummyimage.com/100x100.png/cc0000/ffffff",
      avatar: "https://robohash.org/voluptasquisaut.png?size=150x150&set=set1",
    }
]